Hw2
MIZINCHIK/java-course-2023 pull request #2
Opened 2023-10-15 09:37 UTC by MIZINCHIK

2023-10-17 21:53 UTC, infomouse requested changes

2023-10-17 21:53 UTC, infomouse commented on src/main/java/edu/hw2/Task1/Addition.java
> +package edu.hw2.Task1;
Пакеты надо называть в нижнем регистре.
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

2023-10-17 21:53 UTC, infomouse commented on src/main/java/edu/hw2/Task3/PopularCommandExecutor.java
> +        var connection = manager.getConnection();
Это нужно сделать в блоке try.
try (var connection = manager.getConnection())
Потому что, если мы по каким-то причинам не зайдем в цикл, то мы зря его открывали, да еще и не закроем. Плюс будет более читаемо.

2023-10-17 21:53 UTC, infomouse commented on src/main/java/edu/hw2/Task3/ConnectionManagement/DefaultConnectionManager.java
> +    private final static int FAULTY_CONNECTION_TURN = 5;
Обычно константы объявляются как static final. Еще их группируют вначале класса и отделяют строкой.

2023-10-17 21:53 UTC, infomouse commented on src/main/java/edu/hw2/Task3/ConnectionManagement/DefaultConnectionManager.java
> +    private static int counter = 0;
Этот счетчик не должен быть static, потому что это состояние конкретного объекта, а не всех объектов такого класса. Иначе, если их будет несколько, логика сломается.

2023-10-17 21:53 UTC, infomouse commented on src/main/java/edu/hw2/Task3/Connection/FaultyConnection.java
> +        updateCounter();
Логику обновления счетчика можно перенести в метод isFaultyConnectionTurn. Тогда здесь код будет более лаконичным.
```java
        if (isExceptionTurn()) {
            throw new ConnectionException("Execution failed");
        } else {
            LOGGER.info("Command " + command + " executed");
        }
```

2023-10-17 21:53 UTC, infomouse commented on src/main/java/edu/hw2/Task4/CallingInfo.java
> +            throw new Throwable();
Необязательно его бросать, можно просто создать и вызвать нужный метод.

2023-10-17 21:53 UTC, infomouse commented on src/test/java/edu/hw2/Task3Test.java
> +public class Task3Test {
Заметка на будущее: суть юнит-тестирования заключается в изолированном тестировании каждого класса с логикой. Поэтому и тесты создаются на конкретный класс, в нашем случае должны быть тесты: FaultyConnectionTest, StableConnectionTest и тд. Изолированность достигается за счет мокирования зависимостей. Предлагаю почитать про библиотеку mockito и в следующем ДЗ ее попробовать.

2023-10-17 22:17 UTC, infomouse commented on src/test/java/edu/hw2/Task2Test.java
> +        assertThat(squareAsRectangle.area()).isEqualTo(squareAsSquare.area());
Этот тест не проверяет LSP, потому что не используются методы, которые могут его нарушать.
Например, если в текущей реализации переопределить в квадрате методы:
```java
    @Override
    public Square setWidth(int width) {
        return new Square(width);
    }

    @Override
    public Square setHeight(int height) {
        return new Square(height);
    }
```
Ваш тест пройдет, но LSP нарушено. Тут нужно несколько тестов, пример одного из них:
```java
    private static boolean isLsp(Rectangle rectangle) { // передать new Square(0)
        return rectangle.setHeight(10).setWidth(20).area() == 200;
    }
```
Комментарий не является требованием написать такие тесты 😄

2023-10-22 19:33 UTC, infomouse approved these changes

2023-10-22 19:33 UTC, infomouse commented on src/main/java/edu/hw2/task3/connection/FaultyConnection.java
> +    private static int counter = 0;
Этот счетчик не должен быть static, потому что это состояние конкретного объекта, а не всех объектов такого класса. Иначе, если их будет несколько, логика сломается.

2023-10-28 12:12 UTC, MIZINCHIK commented
Мне имеет смысл ре-реквестить ревью после аппрува, или я сам уже для себя тут исправляю, проверяю и мёрджу?
На всякий случай сделаю так и подобный вопрос оставлю в следующих заданиях для видимости.

2023-10-28 12:20 UTC, MIZINCHIK commented
Оказывается, можно мёрджить отдельные файлы. В следующий раз так буду конфиг файлы менять, так история коммитов должна быть чище (?).

2023-10-30 08:04 UTC, infomouse commented
> Мне имеет смысл ре-реквестить ревью после аппрува, или я сам уже для себя тут исправляю, проверяю и мёрджу? На всякий случай сделаю так и подобный вопрос оставлю в следующих заданиях для видимости.

Если на платформе задача принята, то оставшиеся комментарии можно исправлять по желанию.

2023-11-04 03:53 UTC, merged