Project1
MIZINCHIK/java-course-2023 pull request #3
Opened 2023-10-16 11:34 UTC by MIZINCHIK

2023-10-18 21:27 UTC, infomouse requested changes

2023-10-18 21:27 UTC, infomouse commented on src/main/java/edu/project1/Dictionary/Dictionary.java
> +package edu.project1.Dictionary;
Пакеты надо называть в нижнем регистре.
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

2023-10-18 21:27 UTC, infomouse commented on src/main/java/edu/project1/Util/TerminalWriter.java
> +public class TerminalWriter {
Идея вынести представление в отдельный класс правильная, но реализовывать надо тоже через интерфейс.
Тогда можно будет легко заменить терминал на гуи.

2023-10-18 21:27 UTC, infomouse commented on src/main/java/edu/project1/Controller.java
> +            switch (state.result()) {
Такая логика должна быть в классе, отвечающим за представление. Как показать пользователю текущее состояние игры - задача представления.

2023-10-18 21:27 UTC, infomouse commented on src/main/java/edu/project1/Model/Model.java
> +        State result = new State(new String(userWordMask), correctGuess
В конструкторе не надо делать тернарников. Это не читаемо. Лучше вынести в переменную.

2023-10-18 21:27 UTC, infomouse commented on src/main/java/edu/project1/Model/Model.java
> +    public String getUserWordMask() {
По-хорошему не должно быть таких геттеров. Все общение должно быть через класс State, потому что он точно отражает текущее состояние модели. Геттером же можно получить какое-то промежуточное значение одного поля, при этом сама модель может находится в не консистентном состоянии.

2023-10-21 13:13 UTC, MIZINCHIK commented on src/main/java/edu/project1/Model/Model.java
> +    public String getUserWordMask() {
Теперь метод используется только при получении маски свежевыданного слова.

2023-10-23 18:38 UTC, infomouse approved these changes

2023-10-28 08:31 UTC, merged