Hw6
MIZINCHIK/java-course-2023 pull request #9
Opened 2023-11-12 11:39 UTC by MIZINCHIK

2023-12-10 11:50 UTC, infomouse requested changes

2023-12-10 11:50 UTC, infomouse commented on src/main/java/edu/hw6/task2/FileCloner.java
> +            throw new IllegalArgumentException();
Желательно писать понятный message, что пошло не так в рамках этого класса.

2023-12-10 11:50 UTC, infomouse commented on src/main/java/edu/hw6/task2/FileCloner.java
> +        if (file == null) {
Можно использовать Objects.requireNonNull.

2023-12-10 11:50 UTC, infomouse commented on src/main/java/edu/hw6/task5/HackerNews.java
> +            var response = client.send(request, HttpResponse.BodyHandlers.ofString());
Надо вынести в метод, чтобы не было дублирования кода.

2024-01-13 15:52 UTC, sanyarnd approved these changes

2024-01-29 01:48 UTC, merged